# Generated by Django 6.1.1 on 2026-09-17 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('flight_date', models.DateField()),
                ('airline', models.CharField(max_length=50)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('advance_days', models.PositiveIntegerField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=50)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['origin', 'destination', 'flight_date'], name='airfareinde_origin_1daa89_idx'), models.Index(fields=['advance_days'], name='airfareinde_advance_ebcf1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NationalIndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(unique=True)),
                ('index_value', models.FloatField()),
                ('routes_included', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['observation_date'], name='airfareinde_observa_894caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('weight', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination'), name='unique_route')],
            },
        ),
        migrations.CreateModel(
            name='RouteIndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('avg_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('index_value', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_values', to='airfareindex.route')),
            ],
            options={
                'indexes': [models.Index(fields=['observation_date'], name='airfareinde_observa_564a04_idx')],
                'constraints': [models.UniqueConstraint(fields=('route', 'observation_date'), name='unique_route_index_date')],
            },
        ),
    ]
